# Configuración de la base de datos Oracle
spring.datasource.url: jdbc:oracle:thin:@localhost:1521/xepdb1
spring.datasource.username: pepito
spring.datasource.password: 1234
spring.datasource.driver-class-name: oracle.jdbc.OracleDriver
spring.jpa.show-sql: true

# Otros ajustes específicos de Spring Boot
server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
